import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  id 'org.jetbrains.kotlin.jvm'
  id 'java-gradle-plugin'
}

kotlin {
  jvmToolchain(24)
}

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(24))
  }
}

tasks.withType(KotlinCompile).configureEach {
  compilerOptions {
    jvmTarget = JvmTarget.JVM_24
  }
}

gradlePlugin {
  plugins {
    register('overloadReturn') {
      id = 'com.jakewharton.overloadreturn'
      implementationClass = 'com.jakewharton.overloadreturn.gradle.OverloadReturnPlugin'
    }
  }
}

dependencies {
  compileOnly gradleApi()

  implementation project(':overload-return-compiler')
  implementation deps.androidGradlePlugin
  implementation deps.kotlin
  
  testImplementation deps.junit
  testImplementation deps.truth
}

//apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
