import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  id 'java-library'
}

tasks.withType(JavaCompile).configureEach {
  options.release = 8
}

tasks.withType(KotlinCompile).configureEach {
  compilerOptions {
    jvmTarget = JvmTarget.JVM_1_8
  }
}

//apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
