import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  id 'org.jetbrains.kotlin.jvm'
  id 'application'
}

kotlin {
    jvmToolchain(24)
}

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(24))
  }
}

tasks.withType(KotlinCompile).configureEach {
  compilerOptions {
    jvmTarget = JvmTarget.JVM_24
  }
}

application {
    mainClass = 'com.jakewharton.overloadreturn.compiler.Main'
}

dependencies {
  implementation project(':overload-return-annotations')
  implementation deps.kotlin
  implementation deps.asm
  implementation deps.clikt

  testImplementation deps.junit
  testImplementation deps.compileTesting
  testImplementation deps.asmUtil
  testImplementation deps.jimfs
  testImplementation deps.guava
}

tasks.named('distTar', Tar) {
  enabled = false
}

configurations.named('archives') {
  artifacts.removeAll { it.file =~ 'tar' }
}

assemble.dependsOn(installDist)

//apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
